# Generated by Django 6.0.8 on 2026-09-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity_core", "0003_human"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorganization",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="configuration",
        ),
    ]
