# Generated by Django 6.0.8 on 2026-09-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_core', '0004_drop_organization_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganization',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tags',
        ),
    ]
